version: '3.8'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "6543:5432"
  
  backend:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile  # Dockerfile is in the backend directory
    ports:
      - "1300:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app  # Mount backend directory into the container
